import React from 'react';
import { Loan, CapitalSource, UserProfile, Installment, Agreement, AgreementInstallment, LedgerEntry } from '../../../types';

export interface LoanCardProps {
  loan: Loan;
  sources: CapitalSource[];
  isExpanded: boolean;
  selectedLoanId?: string | null;
  activeUser: UserProfile | null;
  onToggleExpand: (e: React.MouseEvent) => void;
  setSelectedLoanId?: (id: string | null) => void;
  onEdit: (loan: Loan) => void;
  onMessage: (loan: Loan) => void;
  onArchive: (loan: Loan) => void;
  onRestore: (loan: Loan) => void;
  onDelete: (loan: Loan) => void;
  onNote: (loan: Loan) => void;
  onPortalLink: (loan: Loan) => void;
  onUploadPromissoria: (loan: Loan) => void;
  onUploadDoc: (loan: Loan) => void;
  onViewPromissoria: (url: string) => void;
  onViewDoc: (url: string) => void;
  onReviewSignal: (signalId: string, status: 'APROVADO' | 'NEGADO') => void;
  onOpenComprovante: (url: string) => void;
  onReverseTransaction: (transaction: LedgerEntry, loan: Loan) => void;
  onOpenReceipt?: (transaction: LedgerEntry, loan: Loan) => void;
  onRenegotiate: (loan: Loan) => void;
  onActivate: (loan: Loan) => void;
  onAgreementPayment: (loan: Loan, agreement: Agreement, inst: AgreementInstallment, amount?: number, forgiveLateFee?: boolean) => void;
  onReverseAgreementPayment?: (loan: Loan, agreement: Agreement, inst: AgreementInstallment) => void;
  onInstallmentPayment?: (loan: Loan, inst: Installment, debt: any, amount?: number) => void;
  onReverseInstallmentPayment?: (loan: Loan, inst: Installment) => void;
  onRefresh: () => void;
  onMarkAsBilled?: (loan: Loan) => void;
  onNewAporte?: (loan: Loan) => void;
  onToggleCapitalOnly?: (loan: Loan) => void;
  onNavigate?: (id: string) => void;
  onLegalDocument?: (path: string) => void;
  isStealthMode?: boolean;
  allLoans?: Loan[];
}
