-- CapitalFlow — camada de integridade financeira
-- Objetivos:
-- 1) impedir novos estados financeiros impossiveis em parcelas;
-- 2) corrigir a reconciliacao que podia zerar saldo apenas porque o status estava PAID;
-- 3) auditar toda mudanca futura de saldo de fontes e saldo de juros do perfil;
-- 4) disponibilizar um relatorio central de inconsistencias;
-- 5) corrigir somente registros historicos inequivocos (pagamento integral ja registrado, mas saldo remanescente duplicado).

create table if not exists public.financial_balance_audit (
  id bigint generated by default as identity primary key,
  wallet_kind text not null check (wallet_kind in ('SOURCE','PROFILE_INTEREST')),
  entity_id uuid not null,
  profile_id uuid,
  old_balance numeric not null,
  new_balance numeric not null,
  delta numeric not null,
  actor_user_id uuid,
  txid bigint not null default txid_current(),
  changed_at timestamptz not null default now()
);

create index if not exists idx_financial_balance_audit_profile_time
  on public.financial_balance_audit(profile_id, changed_at desc);
create index if not exists idx_financial_balance_audit_entity_time
  on public.financial_balance_audit(entity_id, changed_at desc);

alter table public.financial_balance_audit enable row level security;
revoke all on public.financial_balance_audit from public, anon, authenticated;

create or replace function public.audit_financial_balance_change()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
  if tg_table_name = 'fontes' then
    if round(coalesce(old.balance,0)::numeric,2) is distinct from round(coalesce(new.balance,0)::numeric,2) then
      insert into public.financial_balance_audit(
        wallet_kind, entity_id, profile_id, old_balance, new_balance, delta, actor_user_id
      ) values (
        'SOURCE', new.id, new.profile_id,
        round(coalesce(old.balance,0)::numeric,2),
        round(coalesce(new.balance,0)::numeric,2),
        round((coalesce(new.balance,0)-coalesce(old.balance,0))::numeric,2),
        auth.uid()
      );
    end if;
  elsif tg_table_name = 'perfis' then
    if round(coalesce(old.interest_balance,0)::numeric,2) is distinct from round(coalesce(new.interest_balance,0)::numeric,2) then
      insert into public.financial_balance_audit(
        wallet_kind, entity_id, profile_id, old_balance, new_balance, delta, actor_user_id
      ) values (
        'PROFILE_INTEREST', new.id, new.id,
        round(coalesce(old.interest_balance,0)::numeric,2),
        round(coalesce(new.interest_balance,0)::numeric,2),
        round((coalesce(new.interest_balance,0)-coalesce(old.interest_balance,0))::numeric,2),
        auth.uid()
      );
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.audit_financial_balance_change() from public, anon, authenticated;

drop trigger if exists trg_audit_source_balance on public.fontes;
create trigger trg_audit_source_balance
after update of balance on public.fontes
for each row execute function public.audit_financial_balance_change();

drop trigger if exists trg_audit_profile_interest_balance on public.perfis;
create trigger trg_audit_profile_interest_balance
after update of interest_balance on public.perfis
for each row execute function public.audit_financial_balance_change();

create or replace function public.guard_installment_financial_integrity()
returns trigger
language plpgsql
set search_path = public, extensions, pg_temp
as $$
declare
  v_open numeric;
  v_paid_components numeric;
  v_status text;
begin
  new.principal_remaining := round(coalesce(new.principal_remaining,0)::numeric,2);
  new.interest_remaining := round(coalesce(new.interest_remaining,0)::numeric,2);
  new.late_fee_accrued := round(coalesce(new.late_fee_accrued,0)::numeric,2);
  new.paid_principal := round(coalesce(new.paid_principal,0)::numeric,2);
  new.paid_interest := round(coalesce(new.paid_interest,0)::numeric,2);
  new.paid_late_fee := round(coalesce(new.paid_late_fee,0)::numeric,2);
  new.paid_total := round(coalesce(new.paid_total,0)::numeric,2);

  if new.principal_remaining < -0.005
     or new.interest_remaining < -0.005
     or new.late_fee_accrued < -0.005
     or new.paid_principal < -0.005
     or new.paid_interest < -0.005
     or new.paid_late_fee < -0.005
     or new.paid_total < -0.005 then
    raise exception 'Integridade financeira: valores negativos nao sao permitidos na parcela.';
  end if;

  v_open := round((new.principal_remaining + new.interest_remaining + new.late_fee_accrued)::numeric,2);
  v_paid_components := round((new.paid_principal + new.paid_interest + new.paid_late_fee)::numeric,2);
  v_status := upper(coalesce(new.status,''));

  if abs(new.paid_total - v_paid_components) > 0.05 then
    raise exception 'Integridade financeira: paid_total diverge dos componentes pagos.';
  end if;

  if v_status in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO') and v_open > 0.05 then
    raise exception 'Integridade financeira: parcela nao pode ficar paga com saldo em aberto de %.', v_open;
  end if;

  if v_status in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO') and v_open <= 0.05 then
    new.principal_remaining := 0;
    new.interest_remaining := 0;
    new.late_fee_accrued := 0;
    new.status := 'PAID';
  end if;

  return new;
end;
$$;

revoke all on function public.guard_installment_financial_integrity() from public, anon, authenticated;

-- Reconciliacao historica estritamente segura:
-- status pago + paid_total = componentes pagos = saldo remanescente duplicado.
-- Nao altera valor pago, principal, juros, multa, fonte ou transacao; apenas remove o saldo duplicado.
update public.parcelas
set principal_remaining = 0,
    interest_remaining = 0,
    late_fee_accrued = 0,
    status = 'PAID'
where upper(coalesce(status,'')) in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO')
  and coalesce(paid_total,0) > 0.05
  and abs(
    coalesce(paid_total,0) -
    (coalesce(paid_principal,0)+coalesce(paid_interest,0)+coalesce(paid_late_fee,0))
  ) <= 0.05
  and abs(
    coalesce(paid_total,0) -
    (coalesce(principal_remaining,0)+coalesce(interest_remaining,0)+coalesce(late_fee_accrued,0))
  ) <= 0.05;

drop trigger if exists trg_guard_installment_financial_integrity on public.parcelas;
create trigger trg_guard_installment_financial_integrity
before insert or update of principal_remaining, interest_remaining, late_fee_accrued,
  paid_principal, paid_interest, paid_late_fee, paid_total, status
on public.parcelas
for each row execute function public.guard_installment_financial_integrity();

-- Corrige um comportamento perigoso: status PAID, sozinho, nunca mais apaga saldo real.
create or replace function public.sync_paid_installment_status(
  p_loan_id uuid,
  p_installment_id uuid,
  p_payment_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_remaining numeric;
  v_loan_remaining numeric;
  v_status text;
  v_paid_total numeric;
begin
  select
    round((coalesce(principal_remaining,0)+coalesce(interest_remaining,0)+coalesce(late_fee_accrued,0))::numeric,2),
    upper(coalesce(status,'')),
    round(coalesce(paid_total,0)::numeric,2)
  into v_remaining, v_status, v_paid_total
  from public.parcelas
  where id = p_installment_id and loan_id = p_loan_id
  for update;

  if not found then
    return jsonb_build_object('success',false,'message','Parcela nao encontrada.');
  end if;

  if v_remaining <= 0.05 then
    update public.parcelas
    set principal_remaining = 0,
        interest_remaining = 0,
        late_fee_accrued = 0,
        status = 'PAID',
        paid_date = coalesce(paid_date,p_payment_date)
    where id = p_installment_id and loan_id = p_loan_id;
    v_remaining := 0;
  else
    -- Se um registro historico estiver marcado como pago com saldo, corrige apenas o status.
    -- O saldo financeiro nunca e apagado automaticamente.
    if v_status in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO') then
      update public.parcelas
      set status = case when v_paid_total > 0.05 then 'PARTIAL' else 'PENDING' end
      where id = p_installment_id and loan_id = p_loan_id;
    end if;

    return jsonb_build_object(
      'success',false,
      'message','Parcela ainda possui saldo em aberto.',
      'remaining',v_remaining,
      'status',case when v_paid_total > 0.05 then 'PARTIAL' else 'PENDING' end
    );
  end if;

  select round(coalesce(sum(
    case when upper(coalesce(status,'')) in ('RENEGOCIADO','CANCELADO') then 0
         else coalesce(principal_remaining,0)+coalesce(interest_remaining,0)+coalesce(late_fee_accrued,0)
    end
  ),0)::numeric,2)
  into v_loan_remaining
  from public.parcelas
  where loan_id = p_loan_id;

  if v_loan_remaining <= 0.05 then
    update public.contratos set status='PAID' where id=p_loan_id;
  elsif upper(coalesce((select status from public.contratos where id=p_loan_id),''))='PAID' then
    update public.contratos set status='ATIVO' where id=p_loan_id;
  end if;

  return jsonb_build_object('success',true,'remaining',v_remaining,'loan_remaining',v_loan_remaining);
end;
$$;

-- Visao interna: nao e exposta diretamente ao frontend.
create or replace view public.financial_integrity_issues as
with installment_base as (
  select p.*,
         round((coalesce(p.principal_remaining,0)+coalesce(p.interest_remaining,0)+coalesce(p.late_fee_accrued,0))::numeric,2) as open_balance,
         round((coalesce(p.paid_principal,0)+coalesce(p.paid_interest,0)+coalesce(p.paid_late_fee,0))::numeric,2) as paid_components
  from public.parcelas p
), agreement_base as (
  select ap.*,
         coalesce(nullif(ap.amount,0),nullif(ap.valor,0),0)::numeric as canonical_amount,
         greatest(coalesce(ap.paid_amount,0),coalesce(ap.valor_pago,0))::numeric as canonical_paid
  from public.acordo_parcelas ap
)
select 'INSTALLMENT_PAID_WITH_OPEN_BALANCE'::text issue_type, 'ERROR'::text severity,
       ib.profile_id, 'parcelas'::text entity_table, ib.id entity_id,
       ib.open_balance amount_a, ib.paid_total amount_b,
       jsonb_build_object('status',ib.status,'loan_id',ib.loan_id) details
from installment_base ib
where upper(coalesce(ib.status,'')) in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO') and ib.open_balance>0.05
union all
select 'INSTALLMENT_NEGATIVE_COMPONENT','ERROR',ib.profile_id,'parcelas',ib.id,
       least(coalesce(ib.principal_remaining,0),coalesce(ib.interest_remaining,0),coalesce(ib.late_fee_accrued,0),coalesce(ib.paid_total,0)),
       ib.open_balance,
       jsonb_build_object('loan_id',ib.loan_id)
from installment_base ib
where coalesce(ib.principal_remaining,0)<-0.005 or coalesce(ib.interest_remaining,0)<-0.005
   or coalesce(ib.late_fee_accrued,0)<-0.005 or coalesce(ib.paid_total,0)<-0.005
union all
select 'INSTALLMENT_PAID_COMPONENT_MISMATCH','ERROR',ib.profile_id,'parcelas',ib.id,
       ib.paid_total,ib.paid_components,
       jsonb_build_object('difference',round((ib.paid_total-ib.paid_components)::numeric,2),'loan_id',ib.loan_id)
from installment_base ib
where abs(ib.paid_total-ib.paid_components)>0.05
union all
select 'CONTRACT_PAID_WITH_OPEN_BALANCE','ERROR',coalesce(c.owner_id,c.profile_id),'contratos',c.id,
       round(coalesce(sum(case when upper(coalesce(p.status,'')) in ('RENEGOCIADO','CANCELADO') then 0 else coalesce(p.principal_remaining,0)+coalesce(p.interest_remaining,0)+coalesce(p.late_fee_accrued,0) end),0)::numeric,2),
       c.total_to_receive,
       jsonb_build_object('status',c.status)
from public.contratos c left join public.parcelas p on p.loan_id=c.id
group by c.id,c.owner_id,c.profile_id,c.status,c.total_to_receive
having upper(coalesce(c.status,'')) in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO')
   and coalesce(sum(case when upper(coalesce(p.status,'')) in ('RENEGOCIADO','CANCELADO') then 0 else coalesce(p.principal_remaining,0)+coalesce(p.interest_remaining,0)+coalesce(p.late_fee_accrued,0) end),0)>0.05
union all
select 'AGREEMENT_PAID_OVER_AMOUNT','ERROR',ab.profile_id,'acordo_parcelas',ab.id,
       ab.canonical_amount,ab.canonical_paid,
       jsonb_build_object('status',ab.status,'acordo_id',ab.acordo_id,'numero',ab.numero)
from agreement_base ab
where ab.canonical_paid-ab.canonical_amount>0.05
union all
select 'AGREEMENT_PAID_STATUS_WITH_OPEN_BALANCE','ERROR',ab.profile_id,'acordo_parcelas',ab.id,
       round(greatest(0,ab.canonical_amount-ab.canonical_paid)::numeric,2),ab.canonical_paid,
       jsonb_build_object('status',ab.status,'acordo_id',ab.acordo_id,'numero',ab.numero)
from agreement_base ab
where upper(coalesce(ab.status,'')) in ('PAID','PAGO','QUITADO','QUITADA','FINALIZADO')
  and ab.canonical_amount-ab.canonical_paid>0.05
union all
select 'SOURCE_NEGATIVE_BALANCE','ERROR',f.profile_id,'fontes',f.id,
       round(coalesce(f.balance,0)::numeric,2),null::numeric,
       jsonb_build_object('name',f.name,'archived',f.archived_at is not null)
from public.fontes f where coalesce(f.balance,0)<-0.005
union all
select 'PRINCIPAL_PAYMENT_WITHOUT_SOURCE','ERROR',t.profile_id,'transacoes',t.id,
       round(coalesce(t.amount,0)::numeric,2),round(coalesce(t.principal_delta,0)::numeric,2),
       jsonb_build_object('loan_id',t.loan_id,'idempotency_key',t.idempotency_key,'category',t.category)
from public.transacoes t
where coalesce(t.principal_delta,0)>0.05 and t.source_id is null
  and upper(coalesce(t.category,'')) in ('PAGAMENTO','PRINCIPAL_RETURN')
union all
select 'TRANSACTION_COMPONENT_MISMATCH','ERROR',t.profile_id,'transacoes',t.id,
       round(coalesce(t.amount,0)::numeric,2),
       round((coalesce(t.principal_delta,0)+coalesce(t.interest_delta,0)+coalesce(t.late_fee_delta,0))::numeric,2),
       jsonb_build_object('category',t.category,'type',t.type,'idempotency_key',t.idempotency_key)
from public.transacoes t
where (
    upper(coalesce(t.category,'')) in ('PAGAMENTO','LUCRO')
    or (upper(coalesce(t.category,''))='ESTORNO' and (t.reversed_of_transaction_id is not null
        or coalesce(t.principal_delta,0)<>0 or coalesce(t.interest_delta,0)<>0 or coalesce(t.late_fee_delta,0)<>0))
  )
  and abs(coalesce(t.amount,0)-(coalesce(t.principal_delta,0)+coalesce(t.interest_delta,0)+coalesce(t.late_fee_delta,0)))>0.05;

revoke all on public.financial_integrity_issues from public, anon, authenticated;

create or replace function public.financial_integrity_report(p_profile_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_is_admin boolean := false;
  v_allowed boolean := false;
  v_result jsonb;
begin
  if v_uid is null then
    raise exception 'Sessao autenticada obrigatoria.';
  end if;

  select exists(
    select 1 from public.perfis p
    where (p.user_id=v_uid or p.id=v_uid) and coalesce(p.access_level,99)=1
  ) into v_is_admin;

  if p_profile_id is null then
    if not v_is_admin then
      raise exception 'Perfil obrigatorio para esta sessao.';
    end if;
    v_allowed := true;
  else
    select v_is_admin or exists(
      select 1 from public.perfis p
      where p.id=p_profile_id and (
        p.user_id=v_uid or p.id=v_uid or p.dono_id=v_uid or p.supervisor_id=v_uid or p.owner_profile_id=v_uid
      )
    ) into v_allowed;
  end if;

  if not v_allowed then
    raise exception 'Usuario sem permissao para auditar este perfil.';
  end if;

  select jsonb_build_object(
    'checked_at',now(),
    'profile_id',p_profile_id,
    'healthy',count(*) filter(where severity='ERROR')=0,
    'error_count',count(*) filter(where severity='ERROR'),
    'warning_count',count(*) filter(where severity='WARN'),
    'by_type',coalesce((select jsonb_object_agg(issue_type,cnt) from (
      select issue_type,count(*) cnt from public.financial_integrity_issues
      where p_profile_id is null or profile_id=p_profile_id group by issue_type order by issue_type
    ) s),'{}'::jsonb),
    'issues',coalesce((select jsonb_agg(jsonb_build_object(
      'type',issue_type,'severity',severity,'profile_id',profile_id,'table',entity_table,
      'entity_id',entity_id,'amount_a',amount_a,'amount_b',amount_b,'details',details
    ) order by severity desc,issue_type,entity_id)
    from (select * from public.financial_integrity_issues
          where p_profile_id is null or profile_id=p_profile_id
          limit 200) q),'[]'::jsonb)
  ) into v_result
  from public.financial_integrity_issues i
  where p_profile_id is null or i.profile_id=p_profile_id;

  return v_result;
end;
$$;

revoke all on function public.financial_integrity_report(uuid) from public, anon;
grant execute on function public.financial_integrity_report(uuid) to authenticated;

comment on function public.financial_integrity_report(uuid) is
'Relatorio autenticado de integridade financeira. Nao altera dados; aponta estados impossiveis e divergencias auditaveis.';
